[package]
name = "dtx-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64ct.workspace = true
cddl-cat.workspace = true
ed25519-dalek.workspace = true
oas3.workspace = true
prost-types.workspace = true
protox.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
yaml_serde.workspace = true

[lints]
workspace = true
