use std::{
    fmt::Write as FmtWrite,
    fs,
    io::Write as IoWrite,
    path::Path,
    process::{Command, Stdio},
};

use crate::{
    ErrorRegistry, EventDefinition, EventField, EventRegistry, ProtocolToolError, registry,
};

const RUST_ERRORS_PATH: &str = "crates/dtx-wire/src/generated/errors.rs";
const RUST_EVENTS_PATH: &str = "crates/dtx-wire/src/generated/events.rs";
const DART_ERRORS_PATH: &str = "protocol/generated/dart/lib/src/errors.g.dart";
const DART_EVENTS_PATH: &str = "protocol/generated/dart/lib/src/events.g.dart";

macro_rules! line {
    ($output:expr $(, $argument:expr)* $(,)?) => {
        writeln!($output $(, $argument)*)
            .map_err(|_| ProtocolToolError::new("format generated protocol source"))?
    };
}

/// Renders the server-constructible Rust error enum.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] only if writing to the in-memory source fails.
pub fn render_rust_errors(registry: &ErrorRegistry) -> Result<String, ProtocolToolError> {
    let mut output = String::new();
    output.push_str(
        "// @generated by dtx-protocol from protocol/errors/registry.yaml; do not edit.\n\n\
macro_rules! define_error_codes {\n\
    ($(($variant:ident, $code:literal, $status:literal, $retryable:literal, $message:literal $(,)?)),+ $(,)?) => {\n\
        /// A server-constructible stable v1 API error code.\n\
        #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n\
        pub enum KnownApiErrorCode {\n\
            $($variant),+\n\
        }\n\n\
        impl KnownApiErrorCode {\n\
            /// Every registered v1 code, in registry order.\n\
            pub const ALL: &'static [Self] = &[$(Self::$variant),+];\n\n\
            /// Returns the stable uppercase wire code.\n\
            #[must_use]\n\
            pub const fn as_str(self) -> &'static str {\n\
                match self {\n\
                    $(Self::$variant => $code),+\n\
                }\n\
            }\n\n\
            /// Returns the default HTTP status.\n\
            #[must_use]\n\
            pub const fn http_status(self) -> u16 {\n\
                match self {\n\
                    $(Self::$variant => $status),+\n\
                }\n\
            }\n\n\
            /// Returns whether retrying the same idempotent command is safe by default.\n\
            #[must_use]\n\
            pub const fn default_retryable(self) -> bool {\n\
                match self {\n\
                    $(Self::$variant => $retryable),+\n\
                }\n\
            }\n\n\
            /// Returns the reviewed public default message.\n\
            #[must_use]\n\
            pub const fn default_message(self) -> &'static str {\n\
                match self {\n\
                    $(Self::$variant => $message),+\n\
                }\n\
            }\n\n\
            /// Resolves a registered wire code.\n\
            #[must_use]\n\
            pub fn from_code(value: &str) -> Option<Self> {\n\
                match value {\n\
                    $($code => Some(Self::$variant)),+,\n\
                    _ => None,\n\
                }\n\
            }\n\
        }\n\
    };\n\
}\n\n\
define_error_codes!(\n",
    );
    for error in &registry.errors {
        line!(&mut output, "    (");
        line!(&mut output, "        {},", error.rust_name);
        line!(&mut output, "        {},", quote(&error.code)?);
        line!(&mut output, "        {},", error.http_status);
        line!(&mut output, "        {},", error.default_retryable);
        line!(&mut output, "        {},", quote(&error.message)?);
        line!(&mut output, "    ),");
    }
    output.push_str(");\n");
    Ok(output)
}

/// Renders strict Rust payload structs and registry trait implementations.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] for an unsupported field type or formatting failure.
pub fn render_rust_events(registry: &EventRegistry) -> Result<String, ProtocolToolError> {
    let mut output = String::from(
        "// @generated by dtx-protocol from protocol/events/registry.yaml; do not edit.\n\n",
    );
    render_rust_event_metadata(&mut output, registry)?;
    for event in &registry.events {
        output.push_str(
            "#[derive(Clone, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]\n",
        );
        output.push_str("#[serde(deny_unknown_fields)]\n");
        line!(&mut output, "pub struct {} {{", event.rust_name);
        for field in &event.fields {
            line!(
                &mut output,
                "    pub {}: {},",
                field.name,
                rust_type(&field.field_type)?
            );
        }
        output.push_str("}\n\n");
        line!(
            &mut output,
            "impl crate::RegisteredEventPayload for {} {{",
            event.rust_name
        );
        line!(
            &mut output,
            "    const EVENT_TYPE: &'static str = {};",
            quote(&event.event_type)?
        );
        line!(
            &mut output,
            "    const SCHEMA_VERSION: u16 = {};",
            event.schema_version
        );
        line!(
            &mut output,
            "    const AGGREGATE_TYPE: &'static str = {};",
            quote(&event.aggregate)?
        );
        match &event.required_reader_capability {
            Some(value) => line!(
                &mut output,
                "    const REQUIRED_READER_CAPABILITY: Option<&'static str> = Some({});",
                quote(value)?
            ),
            None => output
                .push_str("    const REQUIRED_READER_CAPABILITY: Option<&'static str> = None;\n"),
        }
        let policy = rust_unknown_version_policy(&event.unknown_version_policy)?;
        line!(
            &mut output,
            "    const UNKNOWN_VERSION_POLICY: crate::UnknownVersionPolicy = crate::UnknownVersionPolicy::{policy};"
        );
        output.push_str("}\n\n");
        line!(
            &mut output,
            "impl crate::CanonicalEncode for {} {{",
            event.rust_name
        );
        output.push_str(
            "    fn to_canonical_value(&self) -> crate::CanonicalValue {\n        crate::CanonicalValue::Map(vec![\n",
        );
        for field in &event.fields {
            output.push_str("            (\n");
            line!(
                &mut output,
                "                crate::CanonicalValue::Unsigned({}),",
                field.key
            );
            line!(
                &mut output,
                "                {},",
                rust_value_expression(field)?
            );
            output.push_str("            ),\n");
        }
        output.push_str("        ])\n    }\n}\n\n");
        render_rust_payload_decoder(&mut output, event)?;
    }
    render_rust_registered_dispatcher(&mut output, registry)?;
    Ok(output)
}

fn render_rust_payload_decoder(
    output: &mut String,
    event: &EventDefinition,
) -> Result<(), ProtocolToolError> {
    line!(
        output,
        "impl crate::CanonicalDecode for {} {{",
        event.rust_name
    );
    output.push_str(
        "    fn decode_canonical(\n\
        value: &crate::CanonicalValue,\n\
    ) -> Result<Self, crate::CanonicalDecodeError> {\n",
    );
    line!(
        output,
        "        let fields = crate::decode_struct_map(value, {})?;",
        event.fields.len()
    );
    output.push_str("        Ok(Self {\n");
    for field in &event.fields {
        line!(
            output,
            "            {}: crate::decode_struct_field(fields, {})?,",
            field.name,
            field.key
        );
    }
    output.push_str("        })\n    }\n}\n\n");
    Ok(())
}

fn render_rust_registered_dispatcher(
    output: &mut String,
    registry: &EventRegistry,
) -> Result<(), ProtocolToolError> {
    output.push_str(
        "/// A fully decoded and integrity-verified registered event envelope.\n\
#[derive(Clone, Debug, Eq, PartialEq)]\n\
pub enum RegisteredEventEnvelope {\n",
    );
    for event in &registry.events {
        line!(output, "    /// Registered `{}`.", event.event_type);
        line!(
            output,
            "    {}(crate::VerifiedEventEnvelope<{}>),",
            event.rust_name,
            event.rust_name
        );
    }
    output.push_str(
        "}\n\n\
macro_rules! decode_registered {\n\
    ($payload:ident, $bytes:expr, $reader:expr) => {\n\
        RegisteredEventEnvelope::$payload(\n\
            crate::EventEnvelopeV1::<$payload>::decode_and_verify($bytes, $reader)?,\n\
        )\n\
    };\n\
}\n\n",
    );
    output.push_str(
        "/// Verifies and decodes a registered event selected by its trusted type/version pair.\n\
///\n\
/// Returns `Ok(None)` only when the integrity-verified pair is not compiled into\n\
/// this reader; callers may then use the opaque-event admission path.\n\
///\n\
/// # Errors\n\
///\n\
/// Returns [`crate::EventIntegrityError`] for malformed, unreadable, tampered,\n\
/// metadata-inconsistent, or schema-invalid registered event bytes.\n\
pub fn decode_registered_event(bytes: &[u8], reader: crate::ProtocolVersion)\n\
    -> Result<Option<RegisteredEventEnvelope>, crate::EventIntegrityError>\n\
{\n\
    let metadata = crate::peek_verified_event_dispatch_metadata(bytes, reader)?;\n\
    let event = match (metadata.event_type().as_str(), metadata.schema_version()) {\n",
    );
    for event in &registry.events {
        line!(
            output,
            "        ({}, {}) => decode_registered!({}, bytes, reader),",
            quote(&event.event_type)?,
            event.schema_version,
            event.rust_name
        );
    }
    output.push_str(
        "        _ => return Ok(None),\n\
    };\n\
    Ok(Some(event))\n\
}\n",
    );
    Ok(())
}

fn render_rust_event_metadata(
    output: &mut String,
    registry: &EventRegistry,
) -> Result<(), ProtocolToolError> {
    output.push_str(
        "/// Immutable metadata for trusted admission of a registered event type.\n\
#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n\
pub struct EventRegistryMetadata {\n\
    /// Payload schema version.\n\
    pub schema_version: u16,\n\
    /// Aggregate family bound to the event type.\n\
    pub aggregate_type: &'static str,\n\
    /// Capability that makes the event required, or `None` for optional events.\n\
    pub required_reader_capability: Option<&'static str>,\n\
    /// Cursor behavior for a payload version the reader does not understand.\n\
    pub unknown_version_policy: crate::UnknownVersionPolicy,\n\
}\n\n\
const EVENT_REGISTRY_METADATA: &[(&str, EventRegistryMetadata)] = &[\n",
    );
    for event in &registry.events {
        let policy = rust_unknown_version_policy(&event.unknown_version_policy)?;
        line!(
            output,
            "    ({}, EventRegistryMetadata {{",
            quote(&event.event_type)?
        );
        line!(output, "        schema_version: {},", event.schema_version);
        line!(
            output,
            "        aggregate_type: {},",
            quote(&event.aggregate)?
        );
        match &event.required_reader_capability {
            Some(value) => line!(
                output,
                "        required_reader_capability: Some({}),",
                quote(value)?
            ),
            None => output.push_str("        required_reader_capability: None,\n"),
        }
        line!(
            output,
            "        unknown_version_policy: crate::UnknownVersionPolicy::{policy},"
        );
        output.push_str("    }),\n");
    }
    output.push_str("];\n\nconst EVENT_REGISTRY_FAMILIES: &[(&str, u16, usize)] = &[\n");
    for (index, event) in registry.events.iter().enumerate() {
        line!(
            output,
            "    ({}, {}, {index}),",
            quote(event_family(event)?)?,
            event.schema_version
        );
    }
    output.push_str(
        "];\n\n\
/// Looks up trusted metadata by the exact registered event type.\n\
#[must_use]\n\
pub fn event_registry_metadata(event_type: &str) -> Option<EventRegistryMetadata> {\n\
    EVENT_REGISTRY_METADATA.iter().find_map(|(registered_type, metadata)| {\n\
        (*registered_type == event_type).then_some(*metadata)\n\
    })\n\
}\n\n\
/// Looks up trusted policy for a canonical future version of a known event family.\n\
#[must_use]\n\
pub fn event_family_metadata(event_type: &str, schema_version: u16)\n\
    -> Option<EventRegistryMetadata>\n\
{\n\
    if event_registry_metadata(event_type).is_some() {\n\
        return None;\n\
    }\n\
    EVENT_REGISTRY_FAMILIES\n\
        .iter()\n\
        .filter_map(|(family, registered_schema_version, metadata_index)| {\n\
            let suffix = event_type.strip_prefix(*family)?.strip_prefix(\".v\")?;\n\
            let encoded_schema_version = canonical_event_schema_suffix(suffix)?;\n\
            (encoded_schema_version == schema_version\n\
                && schema_version > *registered_schema_version)\n\
                .then_some((*registered_schema_version, *metadata_index))\n\
        })\n\
        .max_by_key(|(registered_schema_version, _)| *registered_schema_version)\n\
        .map(|(_, metadata_index)| EVENT_REGISTRY_METADATA[metadata_index].1)\n\
}\n\n\
fn canonical_event_schema_suffix(value: &str) -> Option<u16> {\n\
    if value.is_empty()\n\
        || (value.len() > 1 && value.starts_with('0'))\n\
        || !value.bytes().all(|byte| byte.is_ascii_digit())\n\
    {\n\
        return None;\n\
    }\n\
    value.parse().ok()\n\
}\n\n",
    );
    Ok(())
}

fn event_family(event: &EventDefinition) -> Result<&str, ProtocolToolError> {
    let (family, version) = event
        .event_type
        .rsplit_once(".v")
        .ok_or_else(|| ProtocolToolError::new("versioned event type has no family"))?;
    if version == event.schema_version.to_string() {
        Ok(family)
    } else {
        Err(ProtocolToolError::new(format!(
            "event type {} does not match schema version {}",
            event.event_type, event.schema_version
        )))
    }
}

/// Renders the standalone Dart error registry consumer.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] only for string escaping or formatting failure.
pub fn render_dart_errors(registry: &ErrorRegistry) -> Result<String, ProtocolToolError> {
    let mut output = String::from(
        "// Generated by dtx-protocol from protocol/errors/registry.yaml. Do not edit.\n\n",
    );
    output.push_str("enum KnownApiErrorCode {\n");
    for error in &registry.errors {
        line!(&mut output, "  {},", lower_camel(&error.rust_name));
    }
    output.push_str("}\n\nextension KnownApiErrorCodeWire on KnownApiErrorCode {\n");
    output.push_str("  String get wireCode => switch (this) {\n");
    for error in &registry.errors {
        let variant = lower_camel(&error.rust_name);
        let code = quote(&error.code)?;
        let single_line = format!("    KnownApiErrorCode.{variant} => {code},");
        if single_line.len() <= 80 {
            line!(&mut output, "{single_line}");
        } else {
            line!(&mut output, "    KnownApiErrorCode.{variant} =>");
            line!(&mut output, "      {code},");
        }
    }
    output.push_str("  };\n}\n");
    Ok(output)
}

/// Renders Dart payload classes and canonical-map adapters.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] for an unsupported field type or formatting failure.
pub fn render_dart_events(registry: &EventRegistry) -> Result<String, ProtocolToolError> {
    let mut output = String::from(
        "// Generated by dtx-protocol from protocol/events/registry.yaml. Do not edit.\n\nimport 'wire_helpers.dart';\n\n",
    );
    output.push_str(
        "final class EventMetadata {\n  const EventMetadata({\n    required this.schemaVersion,\n    required this.aggregateType,\n    required this.requiredReaderCapability,\n    required this.unknownVersionPolicy,\n  });\n\n  final int schemaVersion;\n  final String aggregateType;\n  final String? requiredReaderCapability;\n  final String unknownVersionPolicy;\n}\n\nconst eventRegistry = <String, EventMetadata>{\n",
    );
    for event in &registry.events {
        line!(
            &mut output,
            "  {}: EventMetadata(",
            quote(&event.event_type)?
        );
        line!(&mut output, "    schemaVersion: {},", event.schema_version);
        line!(
            &mut output,
            "    aggregateType: {},",
            quote(&event.aggregate)?
        );
        match &event.required_reader_capability {
            Some(value) => line!(
                &mut output,
                "    requiredReaderCapability: {},",
                quote(value)?
            ),
            None => output.push_str("    requiredReaderCapability: null,\n"),
        }
        line!(
            &mut output,
            "    unknownVersionPolicy: {},",
            quote(&event.unknown_version_policy)?
        );
        output.push_str("  ),\n");
    }
    output.push_str("};\n\n");

    for event in &registry.events {
        line!(&mut output, "final class {} {{", event.rust_name);
        line!(&mut output, "  const {}({{", event.rust_name);
        for field in &event.fields {
            line!(
                &mut output,
                "    required this.{},",
                lower_camel(&field.name)
            );
        }
        output.push_str("  });\n\n");
        for field in &event.fields {
            line!(
                &mut output,
                "  final {} {};",
                dart_type(&field.field_type)?,
                lower_camel(&field.name)
            );
        }
        output.push_str("\n  Map<int, Object?> toCanonicalMap() => <int, Object?>{\n");
        for field in &event.fields {
            line!(
                &mut output,
                "    {}: {},",
                field.key,
                dart_value_expression(field)?
            );
        }
        output.push_str("  };\n}\n\n");
    }
    output.pop();
    Ok(output)
}

/// Writes all registry-derived sources.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] for invalid registries, generation, or file I/O.
pub fn generate(root: &Path) -> Result<(), ProtocolToolError> {
    let events = registry::load_event_registry(&root.join("protocol/events/registry.yaml"))?;
    let errors = registry::load_error_registry(&root.join("protocol/errors/registry.yaml"))?;
    write_generated(
        root,
        RUST_EVENTS_PATH,
        &format_rust_source(&render_rust_events(&events)?)?,
    )?;
    write_generated(
        root,
        RUST_ERRORS_PATH,
        &format_rust_source(&render_rust_errors(&errors)?)?,
    )?;
    write_generated(root, DART_EVENTS_PATH, &render_dart_events(&events)?)?;
    write_generated(root, DART_ERRORS_PATH, &render_dart_errors(&errors)?)?;
    Ok(())
}

/// Verifies that committed registry-derived sources exactly match current inputs.
///
/// # Errors
///
/// Returns [`ProtocolToolError`] for invalid registries, missing files, or stale output.
pub fn check_generated(root: &Path) -> Result<(), ProtocolToolError> {
    let events = registry::load_event_registry(&root.join("protocol/events/registry.yaml"))?;
    let errors = registry::load_error_registry(&root.join("protocol/errors/registry.yaml"))?;
    check_one(
        root,
        RUST_EVENTS_PATH,
        &format_rust_source(&render_rust_events(&events)?)?,
    )?;
    check_one(
        root,
        RUST_ERRORS_PATH,
        &format_rust_source(&render_rust_errors(&errors)?)?,
    )?;
    check_one(root, DART_EVENTS_PATH, &render_dart_events(&events)?)?;
    check_one(root, DART_ERRORS_PATH, &render_dart_errors(&errors)?)?;
    Ok(())
}

fn format_rust_source(source: &str) -> Result<String, ProtocolToolError> {
    let mut child = Command::new("rustfmt")
        .args(["--emit", "stdout", "--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| {
            ProtocolToolError::new(format!(
                "start rustfmt for generated protocol source: {error}"
            ))
        })?;
    child
        .stdin
        .take()
        .ok_or_else(|| ProtocolToolError::new("rustfmt stdin was not available"))?
        .write_all(source.as_bytes())
        .map_err(|error| {
            ProtocolToolError::new(format!("write generated source to rustfmt: {error}"))
        })?;
    let output = child.wait_with_output().map_err(|error| {
        ProtocolToolError::new(format!("wait for generated-source rustfmt: {error}"))
    })?;
    if !output.status.success() {
        return Err(ProtocolToolError::new(format!(
            "rustfmt rejected generated protocol source: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    String::from_utf8(output.stdout)
        .map_err(|error| ProtocolToolError::new(format!("rustfmt returned non-UTF-8: {error}")))
}

fn write_generated(root: &Path, relative: &str, source: &str) -> Result<(), ProtocolToolError> {
    let path = root.join(relative);
    let parent = path.parent().ok_or_else(|| {
        ProtocolToolError::new(format!("generated path has no parent: {relative}"))
    })?;
    fs::create_dir_all(parent).map_err(|error| {
        ProtocolToolError::new(format!(
            "create generated directory {}: {error}",
            parent.display()
        ))
    })?;
    fs::write(&path, source).map_err(|error| {
        ProtocolToolError::new(format!("write generated file {}: {error}", path.display()))
    })
}

fn check_one(root: &Path, relative: &str, expected: &str) -> Result<(), ProtocolToolError> {
    let path = root.join(relative);
    let actual = fs::read_to_string(&path).map_err(|error| {
        ProtocolToolError::new(format!("read generated file {}: {error}", path.display()))
    })?;
    if actual == expected {
        Ok(())
    } else {
        Err(ProtocolToolError::new(format!(
            "generated file is stale: {}",
            path.display()
        )))
    }
}

fn rust_type(field_type: &str) -> Result<&'static str, ProtocolToolError> {
    Ok(match field_type {
        "aggregate_id" => "dtx_domain::AggregateId",
        "api_error_code" => "crate::ApiErrorCode",
        "approval_id" => "dtx_domain::ApprovalId",
        "binding_id" => "dtx_domain::BindingId",
        "bool" => "bool",
        "boot_id" => "dtx_domain::BootId",
        "bounded_string" => "crate::BoundedString",
        "connector_id" => "dtx_domain::ConnectorId",
        "consent_id" => "dtx_domain::ConsentId",
        "conversation_id" => "dtx_domain::ConversationId",
        "device_id" => "dtx_domain::DeviceId",
        "directory_registration_id" => "dtx_domain::DirectoryRegistrationId",
        "host_id" => "dtx_domain::HostId",
        "indexer_id" => "dtx_domain::IndexerId",
        "installation_id" => "dtx_domain::InstallationId",
        "job_evidence_id" => "dtx_domain::JobEvidenceId",
        "job_evidence_id_list" => "Vec<dtx_domain::JobEvidenceId>",
        "job_id" => "dtx_domain::JobId",
        "job_resource_id" => "dtx_domain::JobResourceId",
        "job_step_id" => "dtx_domain::JobStepId",
        "managed_service_id" => "dtx_domain::ManagedServiceId",
        "optional_api_error_code" => "Option<crate::ApiErrorCode>",
        "optional_connector_id" => "Option<dtx_domain::ConnectorId>",
        "optional_sha256_digest" => "Option<crate::Sha256Digest>",
        "optional_stable_code" => "Option<crate::StableCode>",
        "optional_utc_millis" => "Option<crate::UtcMillis>",
        "public_subject_id" => "dtx_domain::PublicSubjectId",
        "run_id" => "dtx_domain::RunId",
        "service_operation_id" => "dtx_domain::ServiceOperationId",
        "sha256_digest" => "crate::Sha256Digest",
        "stable_code" => "crate::StableCode",
        "u32" => "u32",
        "u64" => "crate::SafeUint",
        "utc_millis" => "crate::UtcMillis",
        other => {
            return Err(ProtocolToolError::new(format!(
                "unsupported Rust field type {other}"
            )));
        }
    })
}

fn rust_value_expression(field: &EventField) -> Result<String, ProtocolToolError> {
    let name = &field.name;
    Ok(match field.field_type.as_str() {
        "aggregate_id"
        | "approval_id"
        | "binding_id"
        | "boot_id"
        | "connector_id"
        | "consent_id"
        | "conversation_id"
        | "device_id"
        | "directory_registration_id"
        | "host_id"
        | "indexer_id"
        | "installation_id"
        | "job_evidence_id"
        | "job_id"
        | "job_resource_id"
        | "job_step_id"
        | "managed_service_id"
        | "public_subject_id"
        | "run_id"
        | "service_operation_id" => {
            format!("crate::CanonicalValue::Text(self.{name}.to_string())")
        }
        "bounded_string" | "api_error_code" | "sha256_digest" | "stable_code" | "utc_millis" => {
            format!("crate::CanonicalEncode::to_canonical_value(&self.{name})")
        }
        "bool" => format!("crate::CanonicalValue::Bool(self.{name})"),
        "u32" => format!("crate::CanonicalValue::Unsigned(u64::from(self.{name}))"),
        "u64" => format!("crate::CanonicalValue::Unsigned(self.{name}.get())"),
        "optional_connector_id" => format!(
            "self.{name}.as_ref().map_or(crate::CanonicalValue::Null, |value| crate::CanonicalValue::Text(value.to_string()))"
        ),
        "optional_api_error_code"
        | "optional_sha256_digest"
        | "optional_stable_code"
        | "optional_utc_millis" => format!(
            "self.{name}.as_ref().map_or(crate::CanonicalValue::Null, crate::CanonicalEncode::to_canonical_value)"
        ),
        "job_evidence_id_list" => format!(
            "crate::CanonicalValue::Array(self.{name}.iter().map(|value| crate::CanonicalValue::Text(value.to_string())).collect())"
        ),
        other => {
            return Err(ProtocolToolError::new(format!(
                "unsupported canonical field type {other}"
            )));
        }
    })
}

fn dart_type(field_type: &str) -> Result<&'static str, ProtocolToolError> {
    Ok(match field_type {
        "bool" => "bool",
        "u32" | "utc_millis" => "int",
        "u64" => "SafeUint",
        "optional_utc_millis" => "int?",
        "job_evidence_id_list" => "List<String>",
        "optional_api_error_code"
        | "optional_connector_id"
        | "optional_sha256_digest"
        | "optional_stable_code" => "String?",
        "aggregate_id"
        | "api_error_code"
        | "approval_id"
        | "binding_id"
        | "boot_id"
        | "bounded_string"
        | "connector_id"
        | "consent_id"
        | "conversation_id"
        | "device_id"
        | "directory_registration_id"
        | "host_id"
        | "indexer_id"
        | "installation_id"
        | "job_evidence_id"
        | "job_id"
        | "job_resource_id"
        | "job_step_id"
        | "managed_service_id"
        | "public_subject_id"
        | "run_id"
        | "service_operation_id"
        | "sha256_digest"
        | "stable_code" => "String",
        other => {
            return Err(ProtocolToolError::new(format!(
                "unsupported Dart field type {other}"
            )));
        }
    })
}

fn dart_value_expression(field: &EventField) -> Result<String, ProtocolToolError> {
    let name = lower_camel(&field.name);
    Ok(match field.field_type.as_str() {
        "sha256_digest" => format!("decodeSha256({name})"),
        "optional_sha256_digest" => format!("{name} == null ? null : decodeSha256({name}!)"),
        "u64" => format!("{name}.value"),
        _ if rust_type(&field.field_type).is_ok() => name,
        other => {
            return Err(ProtocolToolError::new(format!(
                "unsupported Dart canonical field type {other}"
            )));
        }
    })
}

fn rust_unknown_version_policy(value: &str) -> Result<&'static str, ProtocolToolError> {
    match value {
        "stop_cursor" => Ok("StopCursor"),
        "preserve_and_skip" => Ok("PreserveAndSkip"),
        other => Err(ProtocolToolError::new(format!(
            "unsupported unknown-version policy {other}"
        ))),
    }
}

fn lower_camel(value: &str) -> String {
    if value.contains('_') {
        let mut parts = value.split('_');
        let mut output = parts.next().unwrap_or_default().to_owned();
        for part in parts {
            let mut characters = part.chars();
            if let Some(first) = characters.next() {
                output.extend(first.to_uppercase());
                output.extend(characters);
            }
        }
        output
    } else {
        let mut characters = value.chars();
        let Some(first) = characters.next() else {
            return String::new();
        };
        first.to_lowercase().chain(characters).collect()
    }
}

fn quote(value: &str) -> Result<String, ProtocolToolError> {
    serde_json::to_string(value)
        .map_err(|error| ProtocolToolError::new(format!("quote generated string: {error}")))
}
