-- V30: durable RouteBootstrapV1 control-plane state.
--
-- Recipient and bootstrap capsules remain opaque bounded bytes.  This schema
-- deliberately does not contain MLS state, mailbox descriptors, prompts, or
-- any decrypted capability material.

ALTER TABLE agent.connector_control_operations
    DROP CONSTRAINT connector_control_operations_kind_valid,
    ADD CONSTRAINT connector_control_operations_kind_valid
        CHECK (operation_kind IN (
            'enrollment', 'apply_config', 'rotate_credential', 'close_stream',
            'deliver_agent_provisioning', 'revoke_agent_provisioning',
            'prepare_agent_route_recipient', 'deliver_agent_route_bootstrap'
        ));
ALTER TABLE agent.connector_control_commands
    DROP CONSTRAINT connector_control_commands_kind_valid,
    ADD CONSTRAINT connector_control_commands_kind_valid
        CHECK (command_kind IN (
            'apply_config', 'rotate_credential', 'close_stream',
            'deliver_agent_provisioning', 'revoke_agent_provisioning',
            'prepare_agent_route_recipient', 'deliver_agent_route_bootstrap'
        ));

CREATE TABLE agent.agent_route_bootstraps (
    tenant_id uuid NOT NULL,
    bootstrap_id uuid NOT NULL,
    owner_identity_id text NOT NULL,
    owner_device_id uuid NOT NULL,
    installation_id uuid NOT NULL,
    binding_id uuid NOT NULL,
    agent_control_device_id uuid NOT NULL,
    connector_id uuid NOT NULL,
    -- The route fence is generated by the local MLS import and is absent
    -- until the authenticated Installed receipt is recorded.
    route_fence bytea,
    owner_signed_intent bytea NOT NULL,
    request_digest bytea NOT NULL,
    begin_receipt_bytes bytea NOT NULL,
    begin_receipt_digest bytea NOT NULL,
    recipient_id uuid,
    recipient_capsule_digest bytea,
    opaque_recipient_capsule bytea,
    route_id uuid,
    delivery_id uuid,
    bootstrap_capsule_digest bytea,
    opaque_sealed_bootstrap bytea,
    delivery_request_digest bytea,
    delivery_receipt_bytes bytea,
    delivery_receipt_digest bytea,
    state text NOT NULL,
    rejection_code text,
    expires_at_ms bigint NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    PRIMARY KEY (tenant_id, bootstrap_id),
    CONSTRAINT agent_route_bootstraps_delivery_unique UNIQUE (tenant_id, delivery_id),
    CONSTRAINT agent_route_bootstraps_installation_fk
        FOREIGN KEY (tenant_id, installation_id)
        REFERENCES agent.installations (tenant_id, installation_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_bootstraps_binding_fk
        FOREIGN KEY (tenant_id, binding_id)
        REFERENCES agent.connector_bindings (tenant_id, binding_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_bootstraps_agent_device_fk
        FOREIGN KEY (tenant_id, installation_id, agent_control_device_id)
        REFERENCES agent.agent_devices (tenant_id, installation_id, agent_device_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_bootstraps_connector_fk
        FOREIGN KEY (tenant_id, connector_id)
        REFERENCES agent.connector_instances (tenant_id, connector_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_bootstraps_ids_valid CHECK (
        system.is_uuid_v7(tenant_id)
        AND system.is_uuid_v7(bootstrap_id)
        AND system.is_uuid_v7(owner_device_id)
        AND system.is_uuid_v7(installation_id)
        AND system.is_uuid_v7(binding_id)
        AND system.is_uuid_v7(agent_control_device_id)
        AND system.is_uuid_v7(connector_id)
        AND (recipient_id IS NULL OR system.is_uuid_v7(recipient_id))
        AND (route_id IS NULL OR system.is_uuid_v7(route_id))
        AND (delivery_id IS NULL OR system.is_uuid_v7(delivery_id))
        AND agent.is_public_id(owner_identity_id, 'dtxi1')
    ),
    CONSTRAINT agent_route_bootstraps_values_valid CHECK (
        (route_fence IS NULL OR octet_length(route_fence) = 32)
        AND octet_length(owner_signed_intent) BETWEEN 1 AND 196608
        AND octet_length(request_digest) = 32
        AND octet_length(begin_receipt_bytes) BETWEEN 1 AND 65536
        AND octet_length(begin_receipt_digest) = 32
        AND expires_at_ms BETWEEN 1 AND 253402300799999
        AND created_at_ms BETWEEN 0 AND expires_at_ms - 1
        AND updated_at_ms BETWEEN created_at_ms AND 253402300799999
        AND state IN (
            'pending_recipient', 'recipient_ready', 'pending_delivery',
            'installed', 'rejected', 'expired', 'revoked'
        )
        AND (
            (state = 'pending_recipient'
             AND route_fence IS NULL
             AND recipient_id IS NULL AND recipient_capsule_digest IS NULL
             AND opaque_recipient_capsule IS NULL AND route_id IS NULL
             AND delivery_id IS NULL AND bootstrap_capsule_digest IS NULL
             AND opaque_sealed_bootstrap IS NULL AND delivery_request_digest IS NULL
             AND delivery_receipt_bytes IS NULL AND delivery_receipt_digest IS NULL
             AND rejection_code IS NULL)
            OR (state = 'recipient_ready'
                AND route_fence IS NULL
                AND recipient_id IS NOT NULL AND octet_length(recipient_capsule_digest) = 32
                AND octet_length(opaque_recipient_capsule) BETWEEN 1 AND 196608
                AND route_id IS NULL AND delivery_id IS NULL
                AND bootstrap_capsule_digest IS NULL AND opaque_sealed_bootstrap IS NULL
                AND delivery_request_digest IS NULL AND delivery_receipt_bytes IS NULL
                AND delivery_receipt_digest IS NULL
                AND rejection_code IS NULL)
            OR (state = 'pending_delivery'
                AND route_fence IS NULL
                AND recipient_id IS NOT NULL AND octet_length(recipient_capsule_digest) = 32
                AND octet_length(opaque_recipient_capsule) BETWEEN 1 AND 196608
                AND route_id IS NOT NULL AND delivery_id IS NOT NULL
                AND octet_length(bootstrap_capsule_digest) = 32
                AND octet_length(opaque_sealed_bootstrap) BETWEEN 1 AND 196608
                AND octet_length(delivery_request_digest) = 32
                AND octet_length(delivery_receipt_bytes) BETWEEN 1 AND 65536
                AND octet_length(delivery_receipt_digest) = 32
                AND rejection_code IS NULL)
            OR (state = 'installed'
                AND octet_length(route_fence) = 32
                AND recipient_id IS NOT NULL AND octet_length(recipient_capsule_digest) = 32
                AND octet_length(opaque_recipient_capsule) BETWEEN 1 AND 196608
                AND route_id IS NOT NULL AND delivery_id IS NOT NULL
                AND octet_length(bootstrap_capsule_digest) = 32
                AND octet_length(opaque_sealed_bootstrap) BETWEEN 1 AND 196608
                AND octet_length(delivery_request_digest) = 32
                AND octet_length(delivery_receipt_bytes) BETWEEN 1 AND 65536
                AND octet_length(delivery_receipt_digest) = 32
                AND rejection_code IS NULL)
            OR (state = 'rejected'
                AND route_fence IS NULL
                AND recipient_id IS NOT NULL AND octet_length(recipient_capsule_digest) = 32
                AND octet_length(opaque_recipient_capsule) BETWEEN 1 AND 196608
                AND route_id IS NOT NULL AND delivery_id IS NOT NULL
                AND octet_length(bootstrap_capsule_digest) = 32
                AND octet_length(opaque_sealed_bootstrap) BETWEEN 1 AND 196608
                AND octet_length(delivery_request_digest) = 32
                AND octet_length(delivery_receipt_bytes) BETWEEN 1 AND 65536
                AND octet_length(delivery_receipt_digest) = 32
                AND rejection_code ~ '^[A-Z][A-Z0-9_]{2,63}$')
            OR (state IN ('expired', 'revoked'))
        )
    )
);

-- One owner/device/binding tuple has at most one live bootstrap.  Installed
-- heads are included so an accidental second Begin cannot replace an active
-- route before it is explicitly expired or revoked.
CREATE UNIQUE INDEX agent_route_bootstraps_live_tuple_unique
    ON agent.agent_route_bootstraps (
        tenant_id, owner_identity_id, owner_device_id, installation_id,
        binding_id, agent_control_device_id
    )
    WHERE state IN ('pending_recipient', 'recipient_ready', 'pending_delivery', 'installed');

CREATE TABLE agent.agent_route_bootstrap_outbox (
    tenant_id uuid NOT NULL,
    outbox_id uuid NOT NULL,
    bootstrap_id uuid NOT NULL,
    delivery_id uuid,
    connector_id uuid NOT NULL,
    operation_id uuid NOT NULL,
    command_sequence bigint NOT NULL,
    command_payload_digest bytea NOT NULL,
    encoded_command_digest bytea NOT NULL,
    command_kind text NOT NULL,
    payload_digest bytea NOT NULL,
    opaque_payload bytea NOT NULL,
    state text NOT NULL,
    result_digest bytea,
    resolved_at_ms bigint,
    rejection_code text,
    created_at_ms bigint NOT NULL,
    dispatched_at_ms bigint,
    PRIMARY KEY (tenant_id, outbox_id),
    CONSTRAINT agent_route_bootstrap_outbox_bootstrap_fk
        FOREIGN KEY (tenant_id, bootstrap_id)
        REFERENCES agent.agent_route_bootstraps (tenant_id, bootstrap_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_bootstrap_outbox_ids_valid CHECK (
        system.is_uuid_v7(tenant_id)
        AND system.is_uuid_v7(outbox_id)
        AND system.is_uuid_v7(bootstrap_id)
        AND (delivery_id IS NULL OR system.is_uuid_v7(delivery_id))
        AND system.is_uuid_v7(connector_id)
        AND system.is_uuid_v7(operation_id)
    ),
    CONSTRAINT agent_route_bootstrap_outbox_values_valid CHECK (
        command_kind IN ('prepare_recipient', 'deliver_bootstrap')
        AND command_sequence BETWEEN 1 AND 9007199254740991
        AND octet_length(command_payload_digest) = 32
        AND octet_length(encoded_command_digest) = 32
        AND octet_length(payload_digest) = 32
        AND octet_length(opaque_payload) BETWEEN 1 AND 196608
        AND state IN ('pending', 'dispatched', 'acknowledged', 'rejected', 'cancelled')
        AND created_at_ms BETWEEN 0 AND 253402300799999
        AND (dispatched_at_ms IS NULL OR dispatched_at_ms BETWEEN created_at_ms AND 253402300799999)
        AND (
            (state IN ('pending', 'dispatched', 'cancelled')
             AND result_digest IS NULL AND resolved_at_ms IS NULL AND rejection_code IS NULL)
            OR (state = 'acknowledged'
                AND octet_length(result_digest) = 32
                AND resolved_at_ms BETWEEN created_at_ms AND 253402300799999
                AND rejection_code IS NULL)
            OR (state = 'rejected'
                AND octet_length(result_digest) = 32
                AND resolved_at_ms BETWEEN created_at_ms AND 253402300799999
                AND rejection_code ~ '^[A-Z][A-Z0-9_]{2,63}$')
        )
        AND ((command_kind = 'prepare_recipient' AND delivery_id IS NULL)
          OR (command_kind = 'deliver_bootstrap' AND delivery_id IS NOT NULL))
    )
);

CREATE UNIQUE INDEX agent_route_bootstrap_outbox_prepare_unique
    ON agent.agent_route_bootstrap_outbox (tenant_id, bootstrap_id, command_kind)
    WHERE command_kind = 'prepare_recipient';
CREATE UNIQUE INDEX agent_route_bootstrap_outbox_delivery_unique
    ON agent.agent_route_bootstrap_outbox (tenant_id, delivery_id, command_kind)
    WHERE command_kind = 'deliver_bootstrap';

CREATE TABLE agent.agent_route_binding_heads (
    tenant_id uuid NOT NULL,
    owner_identity_id text NOT NULL,
    owner_device_id uuid NOT NULL,
    installation_id uuid NOT NULL,
    binding_id uuid NOT NULL,
    agent_control_device_id uuid NOT NULL,
    bootstrap_id uuid NOT NULL,
    delivery_id uuid NOT NULL,
    route_id uuid NOT NULL,
    route_fence bytea NOT NULL,
    capsule_digest bytea NOT NULL,
    expires_at_ms bigint NOT NULL,
    installed_at_ms bigint NOT NULL,
    PRIMARY KEY (
        tenant_id, owner_identity_id, owner_device_id, installation_id,
        binding_id, agent_control_device_id
    ),
    CONSTRAINT agent_route_binding_heads_bootstrap_fk
        FOREIGN KEY (tenant_id, bootstrap_id)
        REFERENCES agent.agent_route_bootstraps (tenant_id, bootstrap_id)
        ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT agent_route_binding_heads_ids_valid CHECK (
        system.is_uuid_v7(tenant_id)
        AND system.is_uuid_v7(owner_device_id)
        AND system.is_uuid_v7(installation_id)
        AND system.is_uuid_v7(binding_id)
        AND system.is_uuid_v7(agent_control_device_id)
        AND system.is_uuid_v7(bootstrap_id)
        AND system.is_uuid_v7(delivery_id)
        AND system.is_uuid_v7(route_id)
        AND agent.is_public_id(owner_identity_id, 'dtxi1')
    ),
    CONSTRAINT agent_route_binding_heads_values_valid CHECK (
        octet_length(route_fence) = 32
        AND octet_length(capsule_digest) = 32
        AND installed_at_ms BETWEEN 0 AND expires_at_ms - 1
        AND expires_at_ms BETWEEN 1 AND 253402300799999
    )
);

CREATE UNIQUE INDEX agent_route_binding_heads_route_unique
    ON agent.agent_route_binding_heads (tenant_id, route_id);

ALTER TABLE agent.agent_route_bootstraps ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.agent_route_bootstraps FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.agent_route_bootstraps
    USING (tenant_id = system.current_tenant_id())
    WITH CHECK (tenant_id = system.current_tenant_id());
ALTER TABLE agent.agent_route_bootstrap_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.agent_route_bootstrap_outbox FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.agent_route_bootstrap_outbox
    USING (tenant_id = system.current_tenant_id())
    WITH CHECK (tenant_id = system.current_tenant_id());
ALTER TABLE agent.agent_route_binding_heads ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent.agent_route_binding_heads FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON agent.agent_route_binding_heads
    USING (tenant_id = system.current_tenant_id())
    WITH CHECK (tenant_id = system.current_tenant_id());

REVOKE ALL ON agent.agent_route_bootstraps, agent.agent_route_bootstrap_outbox,
    agent.agent_route_binding_heads FROM PUBLIC;
DO $grant$
BEGIN
    IF to_regrole('dtx_agent_runtime') IS NOT NULL THEN
        GRANT SELECT, INSERT, UPDATE ON agent.agent_route_bootstraps,
            agent.agent_route_bootstrap_outbox, agent.agent_route_binding_heads
            TO dtx_agent_runtime;
    END IF;
END
$grant$;
