[package]
name = "dtx-history-recovery-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dtx-domain = { path = "../dtx-domain" }
dtx-wire = { path = "../dtx-wire" }
ed25519-dalek.workspace = true
uuid.workspace = true

[lints]
workspace = true
