[package]
name = "dtx-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
axum.workspace = true
axum-server.workspace = true
dtx-domain = { path = "../../crates/dtx-domain" }
dtx-group-node = { path = "../dtx-group-node" }
dtx-group-persistence = { path = "../../crates/dtx-group-persistence" }
dtx-identity-node = { path = "../dtx-identity-node" }
dtx-identity-persistence = { path = "../../crates/dtx-identity-persistence" }
dtx-indexer-node = { path = "../dtx-indexer-node" }
dtx-mailbox = { path = "../../crates/dtx-mailbox" }
dtx-mailbox-node = { path = "../dtx-mailbox-node" }
dtx-public-feed-node = { path = "../dtx-public-feed-node" }
ed25519-dalek.workspace = true
sqlx.workspace = true
tokio.workspace = true
rustls.workspace = true
zeroize.workspace = true

[dev-dependencies]
dtx-storage = { path = "../../crates/dtx-storage" }
testcontainers-modules.workspace = true
tower.workspace = true
uuid.workspace = true

[lints]
workspace = true
