#![allow(clippy::missing_errors_doc, clippy::missing_panics_doc)]

use std::{
    collections::HashMap,
    error::Error,
    fmt,
    sync::{Arc, Mutex},
};

use dtx_domain::{JobId, JobResourceId, RequestId, TenantId, WorkerId};
use dtx_security::{
    CrashRequested, ExternalEffectPhase, FaultCheckpoint, FaultHook, FaultPoint, NoFaults,
};

pub type CloudDigest = [u8; 32];

/// Closed, typed request for the first fake AWS mutation capability.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EnsureExecutorRequest {
    operation_id: RequestId,
    tenant_id: TenantId,
    job_id: JobId,
    resource_id: JobResourceId,
    worker_id: WorkerId,
    lease_epoch: u64,
    spec_hash: CloudDigest,
    plan_hash: CloudDigest,
    expires_at_millis: i64,
}

impl EnsureExecutorRequest {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        operation_id: RequestId,
        tenant_id: TenantId,
        job_id: JobId,
        resource_id: JobResourceId,
        worker_id: WorkerId,
        lease_epoch: u64,
        spec_hash: CloudDigest,
        plan_hash: CloudDigest,
        expires_at_millis: i64,
    ) -> Result<Self, FakeAwsError> {
        validate_epoch(lease_epoch)?;
        if expires_at_millis <= 0 {
            return Err(FakeAwsError::InvalidExpiry);
        }
        Ok(Self {
            operation_id,
            tenant_id,
            job_id,
            resource_id,
            worker_id,
            lease_epoch,
            spec_hash,
            plan_hash,
            expires_at_millis,
        })
    }

    #[must_use]
    pub const fn operation_id(&self) -> RequestId {
        self.operation_id
    }
    #[must_use]
    pub const fn tenant_id(&self) -> TenantId {
        self.tenant_id
    }
    #[must_use]
    pub const fn job_id(&self) -> JobId {
        self.job_id
    }
    #[must_use]
    pub const fn resource_id(&self) -> JobResourceId {
        self.resource_id
    }
    #[must_use]
    pub const fn worker_id(&self) -> WorkerId {
        self.worker_id
    }
    #[must_use]
    pub const fn lease_epoch(&self) -> u64 {
        self.lease_epoch
    }
    #[must_use]
    pub const fn spec_hash(&self) -> CloudDigest {
        self.spec_hash
    }
    #[must_use]
    pub const fn plan_hash(&self) -> CloudDigest {
        self.plan_hash
    }
    #[must_use]
    pub const fn expires_at_millis(&self) -> i64 {
        self.expires_at_millis
    }
}

/// Typed read-back request; no provider action name or JSON is accepted.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ObserveExecutorRequest {
    tenant_id: TenantId,
    resource_id: JobResourceId,
}

impl ObserveExecutorRequest {
    #[must_use]
    pub const fn new(tenant_id: TenantId, resource_id: JobResourceId) -> Self {
        Self {
            tenant_id,
            resource_id,
        }
    }
}

/// Typed ephemeral-group destruction request.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DestroyEphemeralGroupRequest {
    operation_id: RequestId,
    tenant_id: TenantId,
    job_id: JobId,
    lease_epoch: u64,
    plan_hash: CloudDigest,
}

impl DestroyEphemeralGroupRequest {
    pub fn new(
        operation_id: RequestId,
        tenant_id: TenantId,
        job_id: JobId,
        lease_epoch: u64,
        plan_hash: CloudDigest,
    ) -> Result<Self, FakeAwsError> {
        validate_epoch(lease_epoch)?;
        Ok(Self {
            operation_id,
            tenant_id,
            job_id,
            lease_epoch,
            plan_hash,
        })
    }
}

fn validate_epoch(epoch: u64) -> Result<(), FakeAwsError> {
    if epoch == 0 {
        Err(FakeAwsError::InvalidLeaseEpoch)
    } else {
        Ok(())
    }
}

/// Mandatory tags generated by the closed capability rather than supplied as a map.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutorTags {
    tenant_id: TenantId,
    job_id: JobId,
    plan_hash: CloudDigest,
    lifecycle: ResourceLifecycle,
    expires_at_millis: i64,
}

/// Typed resource lifetime used by reconciliation and janitor policy tests.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ResourceLifecycle {
    Ephemeral,
    Persistent,
}

impl ExecutorTags {
    #[must_use]
    pub const fn managed(&self) -> bool {
        true
    }
    #[must_use]
    pub const fn tenant_id(&self) -> TenantId {
        self.tenant_id
    }
    #[must_use]
    pub const fn job_id(&self) -> JobId {
        self.job_id
    }
    #[must_use]
    pub const fn plan_hash(&self) -> CloudDigest {
        self.plan_hash
    }
    #[must_use]
    pub const fn lifecycle(&self) -> ResourceLifecycle {
        self.lifecycle
    }
    #[must_use]
    pub const fn expires_at_millis(&self) -> i64 {
        self.expires_at_millis
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ExecutorResourceState {
    Active,
    Destroyed,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutorObservation {
    resource_id: JobResourceId,
    worker_id: WorkerId,
    spec_hash: CloudDigest,
    tags: ExecutorTags,
    state: ExecutorResourceState,
}

impl ExecutorObservation {
    #[must_use]
    pub const fn resource_id(&self) -> JobResourceId {
        self.resource_id
    }
    #[must_use]
    pub const fn worker_id(&self) -> WorkerId {
        self.worker_id
    }
    #[must_use]
    pub const fn spec_hash(&self) -> CloudDigest {
        self.spec_hash
    }
    #[must_use]
    pub const fn tags(&self) -> &ExecutorTags {
        &self.tags
    }
    #[must_use]
    pub const fn state(&self) -> ExecutorResourceState {
        self.state
    }

    fn matches(&self, request: &EnsureExecutorRequest) -> bool {
        self.resource_id == request.resource_id
            && self.worker_id == request.worker_id
            && self.spec_hash == request.spec_hash
            && self.tags.tenant_id == request.tenant_id
            && self.tags.job_id == request.job_id
            && self.tags.plan_hash == request.plan_hash
            && self.tags.lifecycle == ResourceLifecycle::Ephemeral
            && self.tags.expires_at_millis == request.expires_at_millis
            && self.state == ExecutorResourceState::Active
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DestroyEphemeralGroupResult {
    destroyed_count: usize,
}

impl DestroyEphemeralGroupResult {
    #[must_use]
    pub const fn destroyed_count(&self) -> usize {
        self.destroyed_count
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FakeAwsError {
    InvalidLeaseEpoch,
    InvalidExpiry,
    IdempotencyConflict,
    ResourceConflict,
    StaleLease,
    StateUnavailable,
    CrashRequested(CrashRequested),
}

impl fmt::Display for FakeAwsError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::InvalidLeaseEpoch => "lease epoch must be positive",
            Self::InvalidExpiry => "ephemeral expiry must be in the future",
            Self::IdempotencyConflict => "cloud idempotency key was reused with different input",
            Self::ResourceConflict => "cloud resource ID is already claimed by another spec",
            Self::StaleLease => "cloud request used a stale lease",
            Self::StateUnavailable => "fake cloud state is unavailable",
            Self::CrashRequested(_) => "fake cloud crash requested",
        })
    }
}

impl Error for FakeAwsError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::CrashRequested(source) => Some(source),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum AwsCommand {
    Ensure(EnsureExecutorRequest),
    Destroy(DestroyEphemeralGroupRequest),
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum AwsResult {
    Ensure(ExecutorObservation),
    Destroy(DestroyEphemeralGroupResult),
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct CachedAwsResult {
    command: AwsCommand,
    result: AwsResult,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct AwsWorldState {
    resources: HashMap<JobResourceId, ExecutorObservation>,
    results: HashMap<RequestId, CachedAwsResult>,
    job_epochs: HashMap<(TenantId, JobId), u64>,
    attempts: HashMap<RequestId, u32>,
    ensure_effects: usize,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FakeAwsWorldSnapshot(AwsWorldState);

/// Provider-side facts shared by every adapter incarnation.
#[derive(Clone, Debug)]
pub struct FakeAwsWorld {
    state: Arc<Mutex<AwsWorldState>>,
}

impl FakeAwsWorld {
    #[must_use]
    pub fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(AwsWorldState {
                resources: HashMap::new(),
                results: HashMap::new(),
                job_epochs: HashMap::new(),
                attempts: HashMap::new(),
                ensure_effects: 0,
            })),
        }
    }
    #[must_use]
    pub fn snapshot(&self) -> FakeAwsWorldSnapshot {
        FakeAwsWorldSnapshot(
            self.state
                .lock()
                .expect("fake AWS world mutex poisoned")
                .clone(),
        )
    }
    #[must_use]
    pub fn from_snapshot(snapshot: FakeAwsWorldSnapshot) -> Self {
        Self {
            state: Arc::new(Mutex::new(snapshot.0)),
        }
    }
    #[must_use]
    pub fn resource_count(&self) -> usize {
        self.state
            .lock()
            .expect("fake AWS world mutex poisoned")
            .resources
            .len()
    }
    #[must_use]
    pub fn ensure_effect_count(&self) -> usize {
        self.state
            .lock()
            .expect("fake AWS world mutex poisoned")
            .ensure_effects
    }
}

impl Default for FakeAwsWorld {
    fn default() -> Self {
        Self::new()
    }
}

pub struct FakeAwsProvider {
    world: FakeAwsWorld,
    now_millis: i64,
    fault_hook: Arc<dyn FaultHook>,
}

impl fmt::Debug for FakeAwsProvider {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("FakeAwsProvider")
            .field("world", &self.world)
            .field("now_millis", &self.now_millis)
            .field("fault_hook", &"<fault-hook>")
            .finish()
    }
}

impl FakeAwsProvider {
    #[must_use]
    pub fn new(world: FakeAwsWorld, now_millis: i64) -> Self {
        Self::with_fault_hook(world, now_millis, Arc::new(NoFaults))
    }
    #[must_use]
    pub fn with_fault_hook(
        world: FakeAwsWorld,
        now_millis: i64,
        fault_hook: Arc<dyn FaultHook>,
    ) -> Self {
        Self {
            world,
            now_millis,
            fault_hook,
        }
    }

    pub fn ensure_executor(
        &self,
        request: &EnsureExecutorRequest,
    ) -> Result<ExecutorObservation, FakeAwsError> {
        let command = AwsCommand::Ensure(request.clone());
        if let Some(result) = self.cached(request.operation_id, &command)? {
            return match result {
                AwsResult::Ensure(value) => Ok(value),
                AwsResult::Destroy(_) => Err(FakeAwsError::IdempotencyConflict),
            };
        }
        if request.expires_at_millis <= self.now_millis {
            return Err(FakeAwsError::InvalidExpiry);
        }
        let attempt = self.next_attempt(request.operation_id)?;
        self.fault(
            request.operation_id,
            attempt,
            ExternalEffectPhase::BeforeInvoke,
        )?;
        let observation = {
            let mut state = self
                .world
                .state
                .lock()
                .map_err(|_| FakeAwsError::StateUnavailable)?;
            if let Some(cached) = state.results.get(&request.operation_id) {
                if cached.command != command {
                    return Err(FakeAwsError::IdempotencyConflict);
                }
                match &cached.result {
                    AwsResult::Ensure(value) => value.clone(),
                    AwsResult::Destroy(_) => return Err(FakeAwsError::IdempotencyConflict),
                }
            } else {
                let existing = state.resources.get(&request.resource_id).cloned();
                if existing
                    .as_ref()
                    .is_some_and(|value| !value.matches(request))
                {
                    return Err(FakeAwsError::ResourceConflict);
                }
                check_and_advance_epoch(
                    &mut state,
                    request.tenant_id,
                    request.job_id,
                    request.lease_epoch,
                )?;
                let (value, applied) = existing.map_or_else(
                    || {
                        (
                            ExecutorObservation {
                                resource_id: request.resource_id,
                                worker_id: request.worker_id,
                                spec_hash: request.spec_hash,
                                tags: ExecutorTags {
                                    tenant_id: request.tenant_id,
                                    job_id: request.job_id,
                                    plan_hash: request.plan_hash,
                                    lifecycle: ResourceLifecycle::Ephemeral,
                                    expires_at_millis: request.expires_at_millis,
                                },
                                state: ExecutorResourceState::Active,
                            },
                            true,
                        )
                    },
                    |value| (value, false),
                );
                if applied {
                    state.resources.insert(request.resource_id, value.clone());
                    state.ensure_effects += 1;
                }
                state.results.insert(
                    request.operation_id,
                    CachedAwsResult {
                        command,
                        result: AwsResult::Ensure(value.clone()),
                    },
                );
                value
            }
        };
        self.fault(
            request.operation_id,
            attempt,
            ExternalEffectPhase::AfterRemoteCommitBeforeReturn,
        )?;
        Ok(observation)
    }

    pub fn observe_executor(
        &self,
        request: &ObserveExecutorRequest,
    ) -> Result<Option<ExecutorObservation>, FakeAwsError> {
        let state = self
            .world
            .state
            .lock()
            .map_err(|_| FakeAwsError::StateUnavailable)?;
        Ok(state
            .resources
            .get(&request.resource_id)
            .filter(|value| value.tags.tenant_id == request.tenant_id)
            .cloned())
    }

    pub fn destroy_ephemeral_group(
        &self,
        request: &DestroyEphemeralGroupRequest,
    ) -> Result<DestroyEphemeralGroupResult, FakeAwsError> {
        let command = AwsCommand::Destroy(request.clone());
        if let Some(result) = self.cached(request.operation_id, &command)? {
            return match result {
                AwsResult::Destroy(value) => Ok(value),
                AwsResult::Ensure(_) => Err(FakeAwsError::IdempotencyConflict),
            };
        }
        let attempt = self.next_attempt(request.operation_id)?;
        self.fault(
            request.operation_id,
            attempt,
            ExternalEffectPhase::BeforeInvoke,
        )?;
        let result = {
            let mut state = self
                .world
                .state
                .lock()
                .map_err(|_| FakeAwsError::StateUnavailable)?;
            if let Some(cached) = state.results.get(&request.operation_id) {
                if cached.command != command {
                    return Err(FakeAwsError::IdempotencyConflict);
                }
                match &cached.result {
                    AwsResult::Destroy(value) => *value,
                    AwsResult::Ensure(_) => return Err(FakeAwsError::IdempotencyConflict),
                }
            } else {
                check_and_advance_epoch(
                    &mut state,
                    request.tenant_id,
                    request.job_id,
                    request.lease_epoch,
                )?;
                let mut count = 0;
                for value in state.resources.values_mut() {
                    if value.tags.tenant_id == request.tenant_id
                        && value.tags.job_id == request.job_id
                        && value.tags.plan_hash == request.plan_hash
                        && value.state == ExecutorResourceState::Active
                    {
                        value.state = ExecutorResourceState::Destroyed;
                        count += 1;
                    }
                }
                let value = DestroyEphemeralGroupResult {
                    destroyed_count: count,
                };
                state.results.insert(
                    request.operation_id,
                    CachedAwsResult {
                        command,
                        result: AwsResult::Destroy(value),
                    },
                );
                value
            }
        };
        self.fault(
            request.operation_id,
            attempt,
            ExternalEffectPhase::AfterRemoteCommitBeforeReturn,
        )?;
        Ok(result)
    }

    fn cached(
        &self,
        operation_id: RequestId,
        command: &AwsCommand,
    ) -> Result<Option<AwsResult>, FakeAwsError> {
        let state = self
            .world
            .state
            .lock()
            .map_err(|_| FakeAwsError::StateUnavailable)?;
        state.results.get(&operation_id).map_or(Ok(None), |cached| {
            if &cached.command == command {
                Ok(Some(cached.result.clone()))
            } else {
                Err(FakeAwsError::IdempotencyConflict)
            }
        })
    }

    fn fault(
        &self,
        operation_id: RequestId,
        attempt: u32,
        phase: ExternalEffectPhase,
    ) -> Result<(), FakeAwsError> {
        let point =
            FaultPoint::parse("fake_aws_provider").map_err(|_| FakeAwsError::StateUnavailable)?;
        let checkpoint = FaultCheckpoint::new(point, phase, operation_id, attempt)
            .map_err(|_| FakeAwsError::StateUnavailable)?;
        self.fault_hook
            .checkpoint(&checkpoint)
            .map_err(FakeAwsError::CrashRequested)
    }

    fn next_attempt(&self, operation_id: RequestId) -> Result<u32, FakeAwsError> {
        let mut state = self
            .world
            .state
            .lock()
            .map_err(|_| FakeAwsError::StateUnavailable)?;
        let attempt = state.attempts.entry(operation_id).or_default();
        *attempt = attempt
            .checked_add(1)
            .ok_or(FakeAwsError::StateUnavailable)?;
        Ok(*attempt)
    }
}

fn check_and_advance_epoch(
    state: &mut AwsWorldState,
    tenant_id: TenantId,
    job_id: JobId,
    epoch: u64,
) -> Result<(), FakeAwsError> {
    if state
        .job_epochs
        .get(&(tenant_id, job_id))
        .is_some_and(|current| epoch < *current)
    {
        return Err(FakeAwsError::StaleLease);
    }
    state.job_epochs.insert((tenant_id, job_id), epoch);
    Ok(())
}
