[package]
name = "dtx-security"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
dtx-domain = { path = "../dtx-domain" }
dtx-wire = { path = "../dtx-wire" }
rustls.workspace = true
sha2.workspace = true
x509-parser.workspace = true
zeroize.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
